objects/Aux_data__c/Aux_data__c.object-meta.xml
<CustomObject>
    <label>Aux data</label>
    <nameField>
        <displayFormat>ad-{0}</displayFormat>
        <label>Aux data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aux data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/demo/automate extraction components/objects/Aux_data__c/fields/Process_identifier__c.field-meta.xml
<CustomField>
    <fullName>Process_identifier__c</fullName>
    <label>Process identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/KPI_Cleaning_Batch.cls
public with sharing class KPI_Cleaning_Batch implements Database.Batchable<sObject> {
    String identifier;
    public KPI_Cleaning_Batch(String identifier) {
        this.identifier = identifier;
    }

    public List<sObject> start(Database.BatchableContext context) {
        List<sObject> deleteData = [select id from Aux_data__c where Process_identifier__c = :identifier];
        return deleteData;
    }

    public void execute(Database.BatchableContext context, List<sObject> scope) {
        delete scope;
    }

    public void finish(Database.BatchableContext context) {
        // Implement any post-processing logic here
    }

}