receiver/force-app/main/extractor/objects/Connection_config__mdt/Connection_config__mdt.object-meta.xml
<CustomObject>
    <description>This metadata saves the required information to establish the connection to central and self organizations</description>
    <label>Connection config</label>
    <pluralLabel>Connection configs</pluralLabel>
</CustomObject>

receiver/force-app/main/receiver/objects/Connection_config__mdt/fields/Client_id__c.field-meta.xml
<CustomField>
    <fullName>Client_id__c</fullName>
    <description>The client id of the connected app, required for authentication</description>
    <inlineHelpText>The client id of the connected app, required for authentication</inlineHelpText>
    <label>Client id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Connection_config__mdt/fields/Secret_id__c.field-meta.xml
<CustomField>
    <fullName>Secret_id__c</fullName>
    <description>The secret id of the connected app, neccesary for authentication</description>
    <inlineHelpText>The secret id of the connected app, neccesary for authentication</inlineHelpText>
    <label>Secret id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Org_naming__mdt/Org_naming__mdt.object-meta.xml
<CustomObject>
    <description>Object to associate org id to its name</description>
    <label>Org naming</label>
    <pluralLabel>Org namings</pluralLabel>
</CustomObject>

receiver/force-app/main/receiver/objects/Org_naming__mdt/fields/Org_name__c.field-meta.xml
<CustomField>
    <fullName>Org_name__c</fullName>
    <description>The name which will be used when organization is saved</description>
    <inlineHelpText>The name which will be used when organization is saved</inlineHelpText>
    <label>Org name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Organization__c/fields/Org_URL__c.field-meta.xml
<CustomField>
    <fullName>Org_URL__c</fullName>
    <description>Org&apos;s URL</description>
    <inlineHelpText>Org&apos;s URL</inlineHelpText>
    <label>Org URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

receiver/demo/automate extraction components/classes/KPI_Receiver_Batch.cls
public class KPI_Receiver_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts {


    public KPI_Receiver_Batch() {
    }

    public List<sObject> start(Database.BatchableContext context) {
        List<sObject> orgNamings = [select id, Org_name__c  from eext__Org_naming__mdt where eext__Extract_visits_kpi__c = true ];
        List<String> orgNames = new List<String>();
        for (Org_naming__mdt eachMdt: (List<Org_naming__mdt>)orgNamings) {
            orgNames.add(eachMdt.Org_name__c);
        }
        List<sObject> extractOrgs = [select Org_URL__c from Organization__c where Name IN :orgNames];
        return extractOrgs;
    }

    public void execute(Database.BatchableContext context, List<sObject> scope) {
        HttpRequest externalAuthRequest = new HttpRequest();
        Http restHttp = new Http();
        HttpResponse response;
        String externalAccessToken;
        Map<String, Object> externalAuthResponseMap;
        List<Connection_config__mdt> connectionCredentials;
        connectionCredentials = (List<Connection_config__mdt>) database.query('select Client_id__c, Secret_id__c from Connection_config__mdt where DeveloperName = \'alphaMetadata\' Limit 1');

        String externalAuthBody = 'grant_type=client_credentials'
        + '&client_id=' + EncodingUtil.urlEncode(connectionCredentials[0].Client_id__c, 'UTF-8')
        + '&client_secret=' + EncodingUtil.urlEncode(connectionCredentials[0].Secret_id__c, 'UTF-8');

        externalAuthRequest.setMethod('POST');
        externalAuthRequest.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        externalAuthRequest.setBody(externalAuthBody);

        for (Organization__c eachOrg : (List<Organization__c>)scope) {
            System.debug('auth call for ' + eachOrg.Org_URL__c);
            externalAuthRequest.setEndpoint(eachOrg.Org_URL__c + '/services/oauth2/token');
            response = restHttp.send(externalAuthRequest);
            if (response.getStatusCode() == 200) {
                externalAuthResponseMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                externalAccessToken = (String) externalAuthResponseMap.get('access_token');
                AsyncOptions queueOptions = new AsyncOptions();
                queueOptions.MaximumQueueableStackDepth = 1000;

                System.enqueueJob(new KPI_Visits_Queueable(eachOrg.Org_URL__c, externalAccessToken, null), queueOptions);
            } else {
                system.debug('error connection: ' + response.getBody());
            }
        }
    }

    public void finish(Database.BatchableContext context) {
        // Implement any post-processing logic here
    }
}