receiver/force-app/main/receiver/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Organization__c/fields/Last_connection__c.field-meta.xml
<CustomField>
    <fullName>Last_connection__c</fullName>
    <description>The date in which org last connected to the rest service</description>
    <inlineHelpText>The date in which org last connected to the rest service</inlineHelpText>
    <label>Last connection</label>
    <type>Date</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization__c/fields/Org_URL__c.field-meta.xml
<CustomField>
    <fullName>Org_URL__c</fullName>
    <description>Org&apos;s URL</description>
    <inlineHelpText>Org&apos;s URL</inlineHelpText>
    <label>Org URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization__c/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <label>Organization ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <description>The status of the org, depending on whether connection is working correctly, with errors or not at all.</description>
    <inlineHelpText>The status of the org, depending on whether connection is working correctly, with errors or not at all.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receiver/force-app/main/receiver/objects/Organization__c/fields/Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Status_Detail__c</fullName>
    <description>In this field is detailed any problem that has ocurred during the org connection if any</description>
    <inlineHelpText>In this field is detailed any problem that has ocurred during the org connection if any</inlineHelpText>
    <label>Status Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>Username of the user that is configured in the connected app to extract data. Merely informative.</description>
    <inlineHelpText>Username of the user that is configured in the connected app to extract data. Merely informative</inlineHelpText>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/classes/KPI_Receiver_Status.cls
@RestResource(urlMapping='/KPI_Receiver_Status/*')
global with sharing class KPI_Receiver_Status {
    public static OrgInfoWrapper wrapper;

    /*
    *********************************************************
    @Method Name    : checkStatus()
    @author         : cavirjuyar.mejia.tech@bbva.com
    @description    : method called when an error occurs on the target org
                    : to create Organization__c record with error details
    @param          : String orgInfo. json that contains target organization data
    @return         : String 'OK'.
    ********************************************************
    */
    @HttpPost
    global static String checkStatus(String orgInfo) {
        String escapedString = orgInfo.replaceAll('(?<="detail":")(.*)(?=","orgId")', (orgInfo.substringBefore('","orgId"').substringAfter('"detail":"').replaceAll('"','')));
        wrapper = OrgInfoWrapper.parse(escapedString);

        if (!wrapper.detail.containsIgnoreCase('Read timed out')) {

            List<Organization__c> organizations = new List<Organization__c>();
            organizations.add(new Organization__c(Name = KPI_Receiver.getOrgName(wrapper), User__c = wrapper.user, Organization_ID__c = wrapper.orgId,
            Org_URL__c = wrapper.orgUrl, Status__c = wrapper.status ? 'Active' : 'Error', Status_Detail__c = wrapper.detail, Last_connection__c = System.today()));
            if (wrapper.detail.containsIgnoreCase('Unexpected error')) {
                organizations[0].Status__c = 'Error';
            }
            SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.CREATABLE, organizations);
            insert securityDecision.getRecords();
        }
        return 'OK';
    }

}