receiver/force-app/main/receiver/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Organization__c/fields/Last_connection__c.field-meta.xml
<CustomField>
    <fullName>Last_connection__c</fullName>
    <description>The date in which org last connected to the rest service</description>
    <inlineHelpText>The date in which org last connected to the rest service</inlineHelpText>
    <label>Last connection</label>
    <type>Date</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization__c/fields/Organization_ID__c.field-meta.xml
<CustomField>
    <fullName>Organization_ID__c</fullName>
    <label>Organization ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization_version__c/Organization_version__c.object-meta.xml
<CustomObject>
    <label>Organization version</label>
    <nameField>
        <label>Organization version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Organization_version__c/fields/Installed_organization__c.field-meta.xml
<CustomField>
    <fullName>Installed_organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organization from which data is going to be extracted</description>
    <inlineHelpText>Organization from which data is going to be extracted</inlineHelpText>
    <label>Installed organization</label>
    <referenceTo>Organization__c</referenceTo>
    <relationshipLabel>Organization versions</relationshipLabel>
    <relationshipName>Organization_versions</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization_version__c/fields/Newest_package_version__c.field-meta.xml
<CustomField>
    <fullName>Newest_package_version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Newest package version</label>
    <referenceTo>Package_version__c</referenceTo>
    <relationshipLabel>Newest package version</relationshipLabel>
    <relationshipName>Newest_package_version</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization_version__c/fields/Package_version__c.field-meta.xml
<CustomField>
    <fullName>Package_version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object that represents a version of a package</description>
    <inlineHelpText>Object that represents a version of a package</inlineHelpText>
    <label>Package version</label>
    <referenceTo>Package_version__c</referenceTo>
    <relationshipLabel>Organization versions</relationshipLabel>
    <relationshipName>Organization_versions</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Package__c/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package__c/fields/Package_ID__c.field-meta.xml
<CustomField>
    <fullName>Package_ID__c</fullName>
    <label>Package ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package_version__c/Package_version__c.object-meta.xml
<CustomObject>
    <label>Package version</label>
    <nameField>
        <label>Package version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Package_version__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation with the package from which this version is</description>
    <inlineHelpText>Relation with the package from which this version is</inlineHelpText>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Package versions</relationshipLabel>
    <relationshipName>Package_versions</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package_version__c/fields/Version_name__c.field-meta.xml
<CustomField>
    <fullName>Version_name__c</fullName>
    <label>Version name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package_version__c/fields/Version_number__c.field-meta.xml
<CustomField>
    <fullName>Version_number__c</fullName>
    <label>Version number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/classes/KPI_Chart_Controller_Test.cls
@isTest
public with sharing class KPI_Chart_Controller_Test {
    @SuppressWarnings('PMD.AvoidHardcodingId')
    @TestSetup
    static void prepareTest(){
        assignPermissionSet();
        Organization__c newPais = new Organization__c(Name = 'Colombia', Organization_ID__c = 'testOrgId', Last_connection__c = DateTime.now().date().addDays(-20));
        insert newPais;
        Package__c newPackage = new Package__c(Name = 'Product Form', Package_ID__c = '12345678912345k', Namespace__c = 'fprd');
        insert newPackage;
        Package_version__c newVersion = new Package_version__c(Name = 'Product Form 1.43', Version_name__c = 'T-Regex', Version_number__c = '1.43', Package__c = newPackage.Id);
        insert newVersion;
        Organization_version__c orgVersion = new Organization_version__c(Name = 'test orgVer', Package_version__c = newVersion.Id, Newest_package_version__c = newVersion.Id, Installed_organization__c = newPais.Id);
        insert orgVersion;
    }

    @future
    public static void assignPermissionSet() {
        PermissionSet permissionSet = [select Id, Name from permissionset where Name = 'KPI_administrator' limit 1];
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment(
            AssigneeId = currentUser.Id,
            PermissionSetId = permissionSet.Id
            );
        insert permissionSetAssignment;
    }

    @isTest
    public static void testMainClass() {
        User u = [select Id from User where Id = :UserInfo.getUserId() limit 1];
        system.runAs(u) {
            Test.startTest();
            AggregateResult[] groupedResults = [select  MAX(Version_number__c),Package__r.Name  From Package_version__c WITH SECURITY_ENFORCED group by Package__r.Name];
            system.debug(' kav: ' + groupedResults);
            KPI_Chart_Controller.ChartData result = KPI_Chart_Controller.getChartData([select Id From Organization__c limit 1].Id);
            Test.stopTest();
            System.assertEquals(true, result != null, 'value should not be null');
        }
    }
}