receiver/force-app/main/receiver/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Organization_version__c/Organization_version__c.object-meta.xml
<CustomObject>
    <label>Organization version</label>
    <nameField>
        <label>Organization version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Organization_version__c/fields/Installed_organization__c.field-meta.xml
<CustomField>
    <fullName>Installed_organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organization from which data is going to be extracted</description>
    <inlineHelpText>Organization from which data is going to be extracted</inlineHelpText>
    <label>Installed organization</label>
    <referenceTo>Organization__c</referenceTo>
    <relationshipLabel>Organization versions</relationshipLabel>
    <relationshipName>Organization_versions</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization_version__c/fields/Newest_package_version__c.field-meta.xml
<CustomField>
    <fullName>Newest_package_version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Newest package version</label>
    <referenceTo>Package_version__c</referenceTo>
    <relationshipLabel>Newest package version</relationshipLabel>
    <relationshipName>Newest_package_version</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization_version__c/fields/Package_version__c.field-meta.xml
<CustomField>
    <fullName>Package_version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Object that represents a version of a package</description>
    <inlineHelpText>Object that represents a version of a package</inlineHelpText>
    <label>Package version</label>
    <referenceTo>Package_version__c</referenceTo>
    <relationshipLabel>Organization versions</relationshipLabel>
    <relationshipName>Organization_versions</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Organization_version__c/fields/Version_differences__c.field-meta.xml
<CustomField>
    <fullName>Version_differences__c</fullName>
    <label>Version differences</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Package_version__c/Package_version__c.object-meta.xml
<CustomObject>
    <label>Package version</label>
    <nameField>
        <label>Package version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receiver/force-app/main/receiver/objects/Package_version__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation with the package from which this version is</description>
    <inlineHelpText>Relation with the package from which this version is</inlineHelpText>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Package versions</relationshipLabel>
    <relationshipName>Package_versions</relationshipName>
    <type>Lookup</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package_version__c/fields/Version_differences__c.field-meta.xml
<CustomField>
    <fullName>Version_differences__c</fullName>
    <description>Difference of features/bugfixes between last version released and that of the org</description>
    <inlineHelpText>Difference of features/bugfixes between last version released and that of the org</inlineHelpText>
    <label>Version differences</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

receiver/force-app/main/receiver/objects/Package_version__c/fields/Version_number__c.field-meta.xml
<CustomField>
    <fullName>Version_number__c</fullName>
    <label>Version number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

receiver/force-app/main/receiver/classes/KPI_Chart_Controller.cls
public with sharing class KPI_Chart_Controller {
    /*
    *********************************************************
    @Method Name    : getChartData()
    @author         : cavirjuyar.mejia.tech@bbva.com
    @description    : gets and process the data neccesary for creating
                      wanted chart
    @param          : targetOrgRecordId, a String that represents the
                      context record id of the Organization__c object
    @return         : ChartData, inner class enabled for aura
    ********************************************************
    */
    @AuraEnabled
    public static ChartData getChartData(String targetOrgRecordId){
        try {
            List<Organization_version__c> targetOrgVersions = [Select Id, Package_version__r.Version_differences__c, Installed_organization__c, Package_version__r.Version_number__c, Package_version__r.Package__r.Name, Newest_package_version__r.Version_number__c  From Organization_version__c where Installed_organization__c =:targetOrgRecordId WITH SECURITY_ENFORCED];
            ChartData returnChartData = new ChartData();

            for (Organization_version__c eachVpp : targetOrgVersions) {
                returnChartData.packageNames.add(eachVpp.Package_version__r.Package__r.Name);
                returnChartData.installedVersions.add(eachVpp.Package_version__r.Version_number__c);
                returnChartData.latestVersions.add(eachVpp.Newest_package_version__r.Version_number__c );
                returnChartData.differences.add(eachVpp.Package_version__r.Version_differences__c != null ? eachVpp.Package_version__r.Version_differences__c : '');
            }
            return returnChartData;
        } catch (Exception e) {
            return null;
        }
    }

    /*
    *********************************************************
    @Class Name     : ChartData
    @author         : cavirjuyar.mejia.tech@bbva.com
    @description    : wrapper to pass information to aura component
    @property       : List<String> packagesNames. Name of each package,
                      represented on x axis of the chart
    @property       : List<String> installedVersions. In the chart,
                      represents the installed packages dataset
    @property       : List<String> latestVersions. In the chart,
                      represents the latest available package versions
                      dataset
    @property       : List<String> differences. In the chart,
                      represents the features and bugfixes differences
                      of each package
    ********************************************************
    */
    @TestVisible
    class ChartData {
    @AuraEnabled
    public List<String> packageNames = new List<String>();
    @AuraEnabled
    public List<String> installedVersions = new List<String>();
    @AuraEnabled
    public List<String> latestVersions = new List<String>();
    @AuraEnabled
    public List<String> differences  = new List<String>();
    }
}